### PR TITLE
Fix php_pcre_match_impl with 8.4

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by andypost** [comment]
works good, let's get it in

**Review by ghostwriter — APPROVED** [review]
Thank you @remicollet!

**Comment by cmb69** [comment]
Works on Windows (MSVC), too.

**Comment by Jubeki** [comment]
Hey @remicollet thanks for the PR for PHP 8.4 support.

Do you have a timeline for merging / releasing this PR? Will you wait until PHP 8.4 RC1 or GA?

**Comment by remicollet** [comment]
> Do you have a timeline for merging / releasing this PR? Will you wait until PHP 8.4 RC1 or GA?

I always consider it strange to release a new version, stating "Compatible with 8.4" during alpha/beta, which does not have the Final API. So yes, I think it is better to wait for RC1.

BTW, the decision is to the owner, so to @krakjoe

**Comment by andypost** [comment]
API bump/fix will happen in 2 weeks with RC1, this is only fix required to work on 8.4 so better to wait final polishing

**Comment by andypost** [comment]
RC1 is out and API finally fixed, used to rebuild with this patch and no issues detected

**Comment by ghostwriter** [comment]
Joe Watkins aka [`@krakjoe`](https://github.com/krakjoe), needs help.

I encourage you to check out the GoFundMe campaign https://gofund.me/8b6df24f. 

Additionally, sharing the story within your networks can help raise awareness and support.

Thank you for taking the time to read this and for any support you can provide!

**Comment by ariaieboy** [comment]
Is there any update on when this PR is going to get merged?

**Pull request merged**
